# Generated by Django 4.2.5 on 2024-03-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0010_rename_jobtocluser_jobtocluster'),
        ('UserAuth', '0015_feedback'),
    ]

    operations = [
    ]
